### ISSUE TITLE
Problem with adding vivo de ontology extention to vivo

### ISSUE THREAD

**Issue by ramygad** [VIVO-DE/vivo-de-ontology-extension#1]
Hi,

I am trying to add this ontology extension to vivo.
I followed exactly what is mentioned

Installation:
Site Admin -> Add/Remove RDF data
"Or upload a file from your computer": Datei auswählen
"add mixed RDF (instances and/or ontology)" anwählen
Submit

However I was not able to find the a new added classes (which are included in the ontology extension) in the class list (http:/your vivo domain/listVClassWebapps)

Looking forward for your reply.

Best regards,
Ramy Gad

**Comment by ramygad** [comment]
I found out that to install the ontology extensions.
The  vivo-de-0.3.rdf  need to be copied to  yourvivohome/rdf/tbox/filegraph.
then restart vivo
service tomcat8 restart

**Comment by kseuv** [comment]
dear ramy,

which version of vivo do you use?

best regards

kseuv

**Comment by ramygad** [comment]
Hi kseuv,

I used the latest version  VIVO v1.9.1

Best regards,

Ramy
