### ISSUE TITLE
Neuer Release

### ISSUE THREAD

**Issue by tawahle** [VIVO-DE/vivo-de-ontology-extension#11]
Aufgrund der Änderungen in der Modellierung der Klassen, die angedacht sind (siehe https://github.com/VIVO-DE/vivo-de-ontology-extension/wiki/Ontologie--und-%C3%9Cbersetzungs-Call-2018-03-12) schlage ich vor, neue Version der vivo-de - vivo-de-04 zu erstellen.

**Comment by hauschke** [comment]
Ich schlage vor, wir machen daraus ein richtiges Release, von denen wir bisher noch keine hatten. 

https://github.com/VIVO-DE/vivo-de-ontology-extension/releases

Das würde auch nach außen den Entwicklungsfortschritt besser darstellen. Bezüglich der Namensgebung stimme ich zu: Änderungen am Datenmodell (im Gegensatz zu Tippfehlerkorrekturen) sollten auf eine Versionsänderung zumindest auf der .X-Ebene hinauslaufen.

**Comment by hauschke** [comment]
https://github.com/VIVO-DE/vivo-de-ontology-extension/releases/tag/v0.4

Version v0.4 wurde gerade veröffentlicht.
